const seedData = {
  actions: [
    {
      name: "Idle",
      icon: "🧘",
    },
    {
      name:  "Run",
      icon: "🏃",
    },
    {
        name: "Walk",
      icon: "🚶",
    },
    {
        name: "Jump",
      icon: "🤾",
    },
    {
        name: "Rotate Horizontal",
      icon: "↪️",
    },
    {
        name: "Rotate Vertical",
      icon: "↪️",
    },
    {
        name: "Walk",
      icon: "🚶",
    },
    {
        name: "Jump to Idle",
      icon: "🤾⏩🧘",
    },
    {
      slug: "Idle_HitReact2",
        name: "Idle Hit React 2",
      icon: "🧘💥2️⃣",
    },
    {
      slug: "Idle_HitReact1",
        name: "Idle Hit React 1",
      icon: "🧘💥1️⃣",
    },
    {
      slug: "Idle_2_HeadLow",
        name: "Idle 2 Head Low",
      icon: "🧘2️⃣👇",
    },
    {
      slug: "Idle_2",
        name: "Idle 2",
      icon: "🧘2️⃣",
    },
    {
      slug: "Gallop",
        name: "Gallop",
      icon: "🐎",
    },
    {
      slug: "Idle",
        name: "Idle",
      icon: "🧘",
    },
    {
      slug: "Eating",
        name: "Eating",
      icon: "🍴",
    },
    {
      slug: "Death",
        name: "Death",
      icon: "💀",
    },
    {
      slug: "Attack",
        name: "Attack",
      icon: "⚔️",
    },
    {
      slug: "Gallop_Jump",
        name: "Gallop Jump",
      icon: "🐎🤾",
    },
  ],
  creators: [
    {
      slug: "RyanKingArt",
        name: "Ryan King Art"Ryan King Art",
      },
      description: {
        name: "Ryan King Art is a 3D artist who creates 3D models and renders. He is also a YouTuber who shares his knowledge of 3D modeling and rendering."Ryan King Artは3Dモデルとレンダリングを作成する3Dアーティストです。3Dモデリングとレンダリングの知識を共有するYouTuberでもあります。",
      },
      twitter: "https://twitter.com/RyanKingArt",
      website: "https://www.ryankingart.com/",
      youtube: "https://www.youtube.com/channel/UCfjswDVU0XHyBN7UFG0Mi5Q",
      roles: ["creator"],
    },
    {
      slug: "YuriNakanishi",
        name: "Yuri Nakanishi"中西裕理",
      },
      description: {
        name: "Developer of Meshmell"Meshmellの開発者",
      },
      twitter: "https://twitter.com/yurimell6174",
      website: "https://yurimell.com/",
      roles: ["creator", "developer"],
    },
    {
      slug: "RicoCilliers",
        name: "Rico Cilliers"Rico Cilliers",
      },
      description: {
        name: "Technical Director at Polyhaven.com"Polyhaven.comのテクニカルディレクター",
      },
      artStation: "https://www.artstation.com/rico_b3d",
      roles: ["creator"],
    },
    {
      slug: "OliverHarries",
        name: "Oliver Harries"Oliver Harries",
      },
      description: {
        name: "FREELANCE 3D-ARTIST"フリーランス3Dアーティスト",
      },
      website: "https://oliverharries.myportfolio.com/",
      roles: ["creator"],
    },
    {
      slug: "Quaternius",
        name: "Quaternius"Quaternius",
      },
      description: {
        name: "3D-ARTIST"3Dアーティスト",
      },
      website: "https://oliverharries.myportfolio.com/",
      roles: ["creator"],
    },
    {
      slug: "JamesRayCock",
        name: "James Ray Cock"James Ray Cock",
      },
      description: {
        name: "3D Artist for Games and Film."ゲームや映画の3Dアーティスト",
      },
      artStation: "https://www.artstation.com/jamesray",
      roles: ["creator"],
    },
    {
      slug: "SerhiiKhromov",
        name: "Serhii Khromov"Serhii Khromov",
      },
      description: {
        name: "Material/Environment Artist"Material/Environment Artist",
      },
      artStation: "https://www.artstation.com/serhiikhromov",
      roles: ["creator"],
    },
    {
      slug: "RahulChaudhary",
        name: "Rahul Chaudhary"Rahul Chaudhary",
      },
      description: {
        name: "3D Environment and Prop artist"3D Environment and Prop artist",
      },
      artStation: "https://www.artstation.com/rc12",
      roles: ["creator"],
    },
    {
      slug: "KuuttiSiitonen",
        name: "Kuutti Siitonen"Kuutti Siitonen",
      },
      description: {
        name: "3D Artist"3D Artist",
      },
      artStation: "https://www.artstation.com/KuuttiSiitonen",
      paypal: "https://www.paypal.com/paypalme/kuuttis",
      roles: ["creator"],
    },
    {
      slug: "JohnMalcolm",
        name: "John Malcolm"John Malcolm",
      },
      description: {
        name: """,
      },
      roles: ["creator"],
    },
    {
      slug: "UlanCabanilla",
        name: "Ulan Cabanilla"Ulan Cabanilla",
      },
      description: {
        name: """,
      },
      roles: ["creator"],
    },
  ],
  sponsors: [
    {
      id: "1",
        name: "Async Corporation"株式会社Async",
      },
      description: {
        name: """,
      },
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 10000,
    },
    {
      id: "2",
        name: "Francisco D'Anconia"フランシスコ・ダンコニア",
      },
      description: {
        name: """,
      },
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 150000,
    },
    {
      id: "3",
        name: "Kalinin and Associates"カリーニン&アソシエイツ",
      },
      description: {
        name: """,
      },
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 1500,
    },
    {
      id: "4",
        name: "Charles Williams"チャールズ・ウィリアムズ",
      },
      description: {
        name: """,
      },
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 1500,
    },
    {
      id: "5",
        name: "Hiroki Kuroda"黒田博樹",
      },
      description: {
        name: """,
      },
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 1500,
    },
    {
      id: "6",
        name: "Isla Roberts"イスラ・ロバーツ",
      },
      description: {
        name: """,
      },
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 1500,
    },
    {
      id: "7",
        name: "Tracy Garcia"トレーシー・ガルシア",
      },
      description: {
        name: """,
      },
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 1500000,
    },
    {
      id: "8",
        name: "Susan Smith"スーザン・スミス",
      },
      description: {
        name: """,
      },
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 1500,
    },
    {
      id: "9",
        name: "Gelbero.com"ゲルベロ・ドットコム",
      },
      description: {
        name: """,
      },
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 150000,
    },
    {
      id: "10",
        name: "Michael 3D Printing"マイケル3Dプリンティング",
      },
      description: {
        name: """,
      },
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 15000,
    },
    {
      id: "11",
        name: "Margaret O'Brien"マーガレット・オブライエン",
      },
      description: {
        name: """,
      },
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 150,
    },
  ],
  categories: [
    {
      slug: "all",
        name: "All"すべて",
      },
      icon: "🌎",
      color: "bg-emerald-500",
    },
    {
      slug: "suggested",
        name: "Suggested"おすすめ",
      },
      icon: "🔥",
      color: "bg-emerald-500",
    },
    {
      slug: "animal",
        name: "Animal"動物",
      },
      icon: "🐶",
      color: "bg-emerald-500",
    },
    {
      slug: "furniture",
        name: "Furniture"家具",
      },
      icon: "🪑",
      color: "bg-emerald-500",
    },
    {
      slug: "nature",
        name: "Nature"自然",
      },
      icon: "🌳",
      color: "bg-emerald-500",
    },
    {
      slug: "food",
        name: "Food"食べ物",
      },
      icon: "🍔",
      color: "bg-emerald-500",
    },
    {
      slug: "weapon",
        name: "Weapon"武器",
      },
      icon: "🔫",
      color: "bg-emerald-500",
    },
    {
      slug: "lowPoly",
        name: "Low Poly"アニメ風",
      },
      icon: "🟨",
      color: "bg-emerald-500",
    },
    {
      slug: "real",
        name: "Real"リアル",
      },
      icon: "🟦",
      color: "bg-emerald-500",
    },
  ],
  models: [
    {
      slug: "animated_cube",
      resolutions: ["1k"],
      formats: ["glb"],
      usedFormat: "glb",
      scale: 1,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
        name: "Animated Cube"アニメーション付きの立方体",
      },
      description: {
        name: """,
      },
      creator: "YuriNakanishi",
      published: "2024-01-02",
      updated: "2024-01-02",
      categoryTags: ["technology", "real"],
      price: 0,
      license: "CC0",
      credit: "",
      actions: ["rotate_horizontal", "rotate_vertical"],
      isDownloadable: true,
    },
    {
      slug: "sci-fi_worker_robot",
      resolutions: ["1k"],
      formats: ["glb"],
      usedFormat: "glb",
      scale: 0.3,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
        name: "Sci-Fi Worker Robot"SF雑用ロボット",
      },
      description: {
        name: """,
      },
      creator: "YuriNakanishi",
      published: "2024-01-02",
      updated: "2024-01-02",
      categoryTags: ["technology", "real"],
      price: 0,
      license: "CC0",
      credit: "",
      isDownloadable: false,
      source: {
        creator: "RyanKingArt",
        sourceSite: "https://ryankingart.gumroad.com/l/kobsg?layout=profile",
        downloadSite: "https://ryankingart.gumroad.com/l/kobsg?layout=profile",
        sourceVideo: "https://www.youtube.com/watch?v=3zvz1z5t8zA",
      },
    },
    {
      slug: "potted_plant_01",
      resolutions: ["1k"],
      formats: ["glb"],
      usedFormat: "glb",
      scale: 5,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
        name: "Potted plant 01"植木鉢 01",
      },
      description: {
        name: """,
      },
      creator: "RicoCilliers",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/potted_plant_01",
      isDownloadable: true,
    },
    {
      slug: "wooden_crate_01",
      resolutions: ["1k"],
      formats: ["glb"],
      usedFormat: "glb",
      scale: 5,
      rotationDegrees: {
        x: 0,
        y: -90,
        z: 0,
      },
        name: "Wooden Crate 01"木箱",
      },
      description: {
        name: """,
      },
      creator: "JamesRayCock",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/wooden_crate_01",
      isDownloadable: true,
    },
    {
      slug: "wooden_table_02",
      resolutions: ["1k"],
      formats: ["glb"],
      usedFormat: "glb",
      scale: 4,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
        name: "Wooden Table 02"木製のテーブル",
      },
      description: {
        name: """,
      },
      creator: "SerhiiKhromov",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/wooden_table_02",
      isDownloadable: true,
    },
    {
      slug: "food_apple_01",
      resolutions: ["1k"],
      formats: ["glb"],
      usedFormat: "glb",
      scale: 25,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
        name: "Food Apple 01"リンゴ",
      },
      description: {
        name: """,
      },
      creator: "OliverHarries",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "food", "nature", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/food_apple_01",
      isDownloadable: true,
    },
    {
      slug: "fox_01",
      formats: ["glb"],
      usedFormat: "glb",
      scale: 1,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
        name: "Fox"キツネ",
      },
      description: {
        name: """,
      },
      creator: "Quaternius",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["nature", "animal", "lowPoly"],
      price: 0,
      license: "CC0",
      credit: "https://quaternius.com/packs/ultimateanimatedanimals.html",
      actions: [
        "Walk",
        "Jump_ToIdle",
        "Idle_HitReact2",
        "Idle_HitReact1",
        "Idle_2_HeadLow",
        "Idle_2",
        "Idle",
        "Gallop",
        "Eating",
        "Death",
        "Attack",
        "Gallop_Jump",
      ],
      isDownloadable: true,
    },
    {
      slug: "wicker_basket_01",
      resolutions: ["1k"],
      formats: ["glb"],
      usedFormat: "glb",
      scale: 12,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
        name: "Wicker Basket 01"籠 01",
      },
      description: {
        name: """,
      },
      creator: "KuuttiSiitonen",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/wicker_basket_01",
      isDownloadable: true,
    },
    {
      slug: "wooden_handle_saber",
      resolutions: ["1k"],
      formats: ["glb"],
      usedFormat: "glb",
      scale: 4,
      rotationDegrees: {
        x: 0,
        y: 90,
        z: 0,
      },
        name: "Wooden Handle Saber"木製の柄の剣",
      },
      description: {
        name: """,
      },
      creator: "UlanCabanilla",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["weapon", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/wooden_handle_saber",
      isDownloadable: true,
    },
    {
      slug: "wine_barrel_01",
      resolutions: ["1k"],
      formats: ["glb"],
      usedFormat: "glb",
      scale: 5,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
        name: "Wine Barrel 01"ワイン樽",
      },
      description: {
        name: """,
      },
      creator: "JamesRayCock",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/wine_barrel_01",
      isDownloadable: true,
    },
    {
      slug: "wolf_01",
      formats: ["glb"],
      usedFormat: "glb",
      scale: 1.2,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
        name: "Wolf"オオカミ",
      },
      description: {
        name: """,
      },
      creator: "Quaternius",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "nature", "animal", "lowPoly"],
      price: 0,
      license: "CC0",
      credit: "https://quaternius.com/packs/ultimateanimatedanimals.html",
      actions: [
        "Walk",
        "Jump_ToIdle",
        "Idle_HitReact2",
        "Idle_HitReact1",
        "Idle_2_HeadLow",
        "Idle_2",
        "Idle",
        "Gallop",
        "Eating",
        "Death",
        "Attack",
        "Gallop_Jump",
      ],
      isDownloadable: true,
    },
    {
      slug: "book_encyclopedia_set_01",
      resolutions: ["1k"],
      formats: ["glb"],
      usedFormat: "glb",
      scale: 6,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
        name: "Book Encyclopedia Set 01"百科事典の本のセット 01",
      },
      description: {
        name: """,
      },
      creator: "JohnMalcolm",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/book_encyclopedia_set_01",
      isDownloadable: true,
    },
    {
      slug: "round_wooden_table_01",
      resolutions: ["1k"],
      formats: ["glb"],
      usedFormat: "glb",
      scale: 3,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
        name: "Round Wooden Table 01"丸い木製のテーブル 01",
      },
      description: {
        name: """,
      },
      creator: "UlanCabanilla",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/round_wooden_table_01",
      isDownloadable: true,
    },
    {
      slug: "cardboard_box_01",
      resolutions: ["1k"],
      formats: ["glb"],
      usedFormat: "glb",
      scale: 8,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
        name: "Cardboard Box 01"ダンボール箱 01",
      },
      description: {
        name: """,
      },
      creator: "RahulChaudhary",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/cardboard_box_01",
      isDownloadable: true,
    },
    {
      slug: "dining_chair_02",
      resolutions: ["1k"],
      formats: ["glb"],
      usedFormat: "glb",
      scale: 5,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
        name: "Dining Chair 02"ダイニングチェア",
      },
      description: {
        name: """,
      },
      creator: "JamesRayCock",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/dining_chair_02",
      isDownloadable: true,
    },
  ],
};

export default seedData;
